// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_layout.tsx";
import * as $1 from "./routes/api/count.ts";
import * as $2 from "./routes/index.tsx";
import * as $3 from "./routes/notetaking.tsx";
import * as $$0 from "./islands/Counter.tsx";

const manifest = {
  routes: {
    "./routes/_layout.tsx": $0,
    "./routes/api/count.ts": $1,
    "./routes/index.tsx": $2,
    "./routes/notetaking.tsx": $3,
  },
  islands: {
    "./islands/Counter.tsx": $$0,
  },
  baseUrl: import.meta.url,
};

export default manifest;
